/**
 * Create a test document linked to STU-54 for UI verification
 */

import { LinearClient } from '@linear/sdk';

const LINEAR_API_KEY = process.env.LINEAR_API_KEY;
const TEST_ISSUE_ID = process.env.TEST_ISSUE_ID || 'd85399b4-0706-4dfd-966e-8116a9324eb1'; // STU-54

if (!LINEAR_API_KEY) {
  console.error('❌ Error: LINEAR_API_KEY environment variable is required');
  process.exit(1);
}

async function main() {
  const client = new LinearClient({ apiKey: LINEAR_API_KEY });
  const issue = await client.issue(TEST_ISSUE_ID);

  console.log(`Creating document linked to ${issue.identifier}...\n`);

  const createResult = await client.createDocument({
    title: `${issue.identifier} - User Story`,
    content: `# User Story

> Generated by DevFlow - Phase 2: User Story

---

## Story

**As a** user of the DevFlow platform
**I want** to login with my email and password
**So that** I can access my personalized dashboard and manage my tasks

---

## Acceptance Criteria

1. ✅ Login endpoint accepts email and password via POST request
2. ✅ Valid credentials return JWT token with 1h expiration
3. ✅ Invalid credentials return 401 with specific error messages:
   - "Email not found" for unknown email
   - "Invalid password" for wrong password
   - "Account locked" after 5 failed attempts
4. ✅ Rate limiting: 5 attempts per 15 minutes
5. ✅ Account lockout: 15 minutes, auto-unlock

---

## Definition of Done

- [ ] Unit tests pass (>80% coverage)
- [ ] E2E tests cover: login success, login failure, lockout, token refresh
- [ ] GDPR compliant logging (no passwords stored)
- [ ] Code reviewed and approved
- [ ] Documentation updated

---

## Business Value

This feature is critical for platform security and user trust. It enables:
- Secure access control
- Personalized user experience
- Compliance with security requirements

**Story Points:** 8 (Fibonacci)

---

## 🧠 LLM Council Deliberation

**Council:** claude-sonnet-4, gpt-4o, gemini-2.0-flash-exp
**Chairman:** claude-sonnet-4

| Rank | Model | Avg Position |
|------|-------|--------------|
| 🥇 | claude-sonnet-4 | 1.33 |
| 🥈 | gpt-4o | 2.00 |

**Agreement:** 🟢 HIGH

---

*Generated by DevFlow at ${new Date().toISOString()}*`,
    issueId: TEST_ISSUE_ID,
  } as any);

  const doc = await createResult.document;

  console.log('✅ Document created!');
  console.log(`   Title: ${doc?.title}`);
  console.log(`   URL: ${doc?.url}`);
  console.log(`   ID: ${doc?.id}`);
  console.log('\n👀 Check Linear UI to see the document linked to the issue!');
  console.log(`   Issue: https://linear.app/studio-nomad/issue/${issue.identifier}`);
}

main().catch(console.error);
